### ISSUE TITLE
PHP SOAP extension missing for pantheon site

### ISSUE THREAD

**Issue by aaronbauman** [kalabox/lando#225]
kbox v2.1.3 
macOS Sierra version 10.12.1

- pantheon / drupal app which requires SoapClient (via PHP SOAP extension)
- works great on pantheon platform
- pulled down a pantheon site EXAMPLE to work locally
- tried to clear cache with "kbox drush cc all"
- got an error indicating missing PHP SOAP extension, missing class SoapClient
- followed some steps from https://github.com/kalabox/kalabox/issues/1750 to install php soap on the app server: 
`$ docker exec -i -t EXAMPLE_appserver_1 /bin/bash`
`$ apt-get install php-soap -y`
`$ docker-php-ext-install soap`
- `php -i` in docker shell confirms that soap extension is installed
- restarted site via kalabox UI
- same error undefined class SoapClient

**Comment by pirog** [comment]
@aaronbauman AFAICT SOAP is already locked and loaded on lando pantheon appz

**Comment by aaronbauman** [comment]
@pirog any pointers on helping to resolve this issue then?

Some component of kalabox is definitely broken, since I'm still getting the "missing SoapClient" error.
Pantheon support sent me to Kalabox.
Kalabox sent me here, so i have no idea where to go now.

**Comment by pirog** [comment]
@aaronbauman i dont think you need to go anywhere else. i'd just swap out kalabox for lando and spin up your pantheon site that way. Here is the most useful documentation to that end: https://docs.lndo.io/tutorials/pantheon.html

For clarification on the Lando/Kalabox relationship. Lando is what we are calling Kalabox 3.0. It's currently in late beta phase and is also currently CLI only. That said we are starting to encourage people who are experiencing pain points with kalabox to try lando since its likely those pain points have been addressed in lando and will not be addressed in kalabox. 

We are also working with Pantheon to manage this transition but its still early stages.

**Comment by aaronbauman** [comment]
Great, thank you for the explainer, I will try it out.
