### ISSUE TITLE
Pantheon database will not pull due to size of BLOB/TEXT data

### ISSUE THREAD

**Issue by Senpai** [kalabox/lando#313]
Error noted during `lando pull`:

```
Pulling database...
ERROR 1118 (42000) at line 11645: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.
```

**Comment by pirog** [comment]
@Senpai i was able to replicate this. Boosting log size to see if that helps.

**Comment by pirog** [comment]
@Senpai yeah boosting the log size seems to work for me, we should definitely default our config to the "does it work" side of things so im going to roll out a fix to bump the log size.

That said its probably also worth investigating why such a large single transaction exists in the database to begin with since im guessing such a thing might manifest itself in other ugly ways. Probably worth pinging @reynoldsalec on that.
